# Generated by Django 5.2 on 2025-05-03 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_post_media"),
    ]

    operations = []
