# Generated by Django 5.2 on 2025-05-06 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_group_groupmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmessage",
            name="media",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="group_messages/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "mp4",
                            "mov",
                            "avi",
                        ]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="media",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="messages/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "mp4",
                            "mov",
                            "avi",
                        ]
                    )
                ],
            ),
        ),
    ]
